export const PLUGIN_NAME = 'sanityblog'
export const PLUGIN_VERSION = '0.2.0'
export const DEFAULT_PUBLISHER_API_ORIGIN = 'https://publish.miyaip.com'
export const DEFAULT_SANITY_API_VERSION = '2026-07-05'
export const DEFAULT_PUBLIC_SITE_ORIGIN = 'https://miyaip.com'
